### ISSUE TITLE
aggregate with floor

### ISSUE THREAD

**Issue by einhverfr** [adjust/istore#84]
We should have an aggregate with a floor that one can sum istores together with a floor value.  The idea is to filter out, for example, invalid negative numbers.

Proposed invocation:

    sum_floor(istorecol, int)

Example:

GIven the following istores in a column called myval:

     {1 => 3, 2 => -2, 3 => 4 }
     {1 => -3, 2 => 5, 3 => 15}
     {1 => 2, 2 => -3, 3 => -1, 4 => -3}

Then:

     sum_floor(myval, 0)

would generate

     {1 => 5, 2 => 5, 3 => 19}

**Comment by rapimo** [comment]
I'd prefere more generic option to achieve this.
I.e. we already have `compact(istore)` and `istore_val_larger(istore, istore)`
How about adding `istore_val_larger(istore, int)` so that

`SELECT istore_val_larger({1 => 2, 2 => -3, 3 => -1, 4 => -3}, 0)` gives
`{1 => 2}`
on could then `SUM(istore_val_larger(istore_col,int)` to achieve the same.

functionality would be the same as `clamp_below` just with values instead of keys

**Comment by ildus** [comment]
I think @alexeyklyukin is already working on this in #86. Problem with these functions that the function should make another istore and allocate more memory on each tuple.

**Comment by alexeyklyukin** [comment]
> I think @alexeyklyukin is already working on this in #86. Problem with these functions that the function should make another istore and allocate more memory on each tuple.

Chris came up with the idea to avoid that by introducing a checker function to see if the istore values are within the given [bigint] boundaries. For the case we have at hand we could just isolate the problematic values and run the normal sum on the others; perhaps the function proposed here would also be of a help, as we could run it separately on the values that have negatives in it, i..e
`case when istore_lower_than(column, 0) then sum_floor(column, 0) else sum(column)  end as column_name`.

**Comment by einhverfr** [comment]
Yeah my thinking was this function would be more efficient than creating new istores and summing.

I can see two ways of looking at this.
1.  With faster hardware, we need to worry less about this efficiency.
2.  With faster hardware, we are catching up with the hardware fast enough to make this have a possibly significant difference.

**Comment by rapimo** [comment]
well efficiency is always good, I was just wondering about the use cases because this alone seems not to be a full api ppl might also want to check equality or less than, so maybe

`sum_if_val(istorecol, op, int)` would be a more flexible thing ?
`SELECT sum_if_val(col, '>', 0)`  

Not sure how the implementation would end up performance wise though

**Comment by ildus** [comment]
Thinking about the performance, it could be better to just generate the code for each operator, and in the end we will have five different functions like: `sum_gt`, `sum_gte`, `sum_eq`, `sum_lt` and `sum_lte`. And same for other aggregation functions.

**Comment by alexeyklyukin** [comment]
In the vast majority of cases we aggregate with the `sum`; the idea of a specialized aggregate here comes from the desire to avoid doing two passes over a single `istore` (one to correct values and another to accumulate values for the keys) and allocate memory for the `istores` that don't need to be changed.

The less-common cases are covered by #86: one can filter on `istore_in_range` function  before passing the `istore` to the respective aggregate or apply `istore_floor`/`istore_ceiling` ones to correct them.

**Comment by einhverfr** [comment]
Not sure this is needed anymore or has a legitimate use case.  closing.
